title: Abdullah Nafees
email: abdullahnafees23 [at] gmail [dot] com
description: "An overly excited computer scientist from Lahore, Pakistan"
baseurl: ""
url: "https://abdnafees.github.io" 
twitter_username: abdnafees
github_username:  abdnafees

# Build settings
theme: minima
plugins:
  - jekyll-feed